export const LOAD_LABELS_START = 'LOAD_LABELS_START';
export const LOAD_LABELS_SUCCESS = 'LOAD_LABELS_SUCCESS';
export const LOAD_LABELS_ERROR = 'LOAD_LABELS_ERROR';

export const REMOVE_LABEL_SUCCESS = 'REMOVE_LABEL_SUCCESS';
export const REMOVE_LABEL_ERROR = 'REMOVE_LABEL_ERROR';

export const CREATE_LABEL_SUCCESS = 'CREATE_LABEL_SUCCESS';

export const RECEIVE_LABEL = 'RECEIVE_LABEL';

export const EDIT_LABEL = 'EDIT_LABEL';

export const SHOW_MANAGE_LABELS_MODAL = 'SHOW_MANAGE_LABELS_MODAL';
export const HIDE_MANAGE_LABELS_MODAL = 'HIDE_MANAGE_LABELS_MODAL';